name: Vercel Preview Deployment

on:
  repository_dispatch:
    types: [preview-command]

permissions:
  contents: read

concurrency:
  group: preview-pr-${{ github.event.client_payload.github.payload.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.sha }}

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.11"

      - name: Install
        run: bun install --frozen-lockfile

      - name: Declare some variables
        run: |
          echo "NEXT_PUBLIC_GIT_COMMIT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Build
        run: bun run build

#      - name: Pull Vercel Environment Information
#        run: bun vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
#
#      - name: Build Project Artifacts
#        run: bun vercel build --token=${{ secrets.VERCEL_TOKEN }}
#
#      - name: Deploy Project Artifacts to Vercel
#        run: bun vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          bunx netlify deploy \
            --dir out \
            --no-build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
